kind: pipeline
name: default

steps:
- name: test
  image: node
  commands:
  - npm install
  - npm test
- name: publish  
  image: plugins/ecr
  settings:
    access_key:
      from_secret: AWS_ACCESS_KEY_ID
    secret_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    region: us-east-2
    repo: test
    registry: 728600357975.dkr.ecr.us-east-2.amazonaws.com
    tags:
    - ${DRONE_COMMIT:0:7}
    - latest
    insecure: true
    create_repository: true
- name: deploy
  image: joshdvir/drone-ecs-deploy
  settings:
    cluster: app-cluster
    service: app-first-service
    aws_access_key_id:
      from_secret: AWS_ACCESS_KEY_ID
    aws_secret_access_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
    image_name: 728600357975.dkr.ecr.us-east-2.amazonaws.com/test:latest
    aws_region: us-east-2