kind: pipeline
name: default

steps:
- name: test
  image: node
  commands:
  - npm install
  - npm test
- name: publish  
  image: plugins/ecr
  settings:
    access_key:
      from_secret: AWS_ACCESS_KEY_ID
    secret_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    region: us-east-2
    repo: test
    registry: 728600357975.dkr.ecr.us-east-2.amazonaws.com
    tags:
    - ${DRONE_COMMIT:0:7}
    - latest
    insecure: true
    create_repository: true

- name: deploy
  image: alpine
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  commands:
  - apk update && apk add zip
  - apk --no-cache add ca-certificates curl bash jq py2-pip
  - pip install awscli
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set default.region us-east-2
  - aws ecs update-service --cluster app-cluster --service app-first-service --force-new-deployment --region us-east-2
